name: dotnet package

on: [push]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: build-results
          path: 'WindowPositionAssistant\\bin\\Release'
